import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"
TERMINAL = "alacritty"

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[scrolling]
history = 10000

[window]
decorations = "none"
dynamic_title = true
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0
