# Dotter global configuration file
# https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration

[git.files]
# https://git-scm.com/docs/git-config
"git/gitconfig" = "~/.gitconfig"

[fish]
# https://fishshell.com/

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/nnn.fish" = "~/.config/fish/nnn.fish"
"fish/fzf.fish" = "~/.config/fish/fzf.fish"
"fish/fish_plugins" = "~/.config/fish/fish_plugins"

[alacritty.files]
# https://alacritty.org/config-alacritty.html
"alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"
"alacritty/catppuccin-frappe.toml" = "~/.config/alacritty/catppuccin-frappe.toml"

[atuin.files]
# https://docs.atuin.sh/configuration/config/
"atuin/config.toml" = "~/.config/atuin/config.toml"

[neovim.files]
# https://neovim.io/doc/user/starting.html
"nvim" = "~/.config/nvim"

[bat.files]
# https://github.com/sharkdp/bat
"bat/config" = "~/.config/bat/config"

[delta.files]
# https://dandavison.github.io/delta/
"delta" = "~/.config/delta"

[lazygit.files]
# https://github.com/jesseduffield/lazygit
"lazygit/config.yml" = { target = "~/Library/Application Support/lazygit/config.yml", type = "symbolic" }

[starship.files]
# https://starship.rs/config/
"starship/starship.toml" = "~/.config/starship.toml"

[hammerspoon.files]
# https://www.hammerspoon.org/docs/
"hammerspoon/init.lua" = "~/.hammerspoon/init.lua"
"hammerspoon/alacritty.lua" = { target = "~/.hammerspoon/alacritty.lua", type = "symbolic", if = "dotter.packages.alacritty" }

[just.files]
# https://just.systems/man/en/
"just/.justfile" = "~/.justfile"

[tmux.files]
# https://github.com/tmux/tmux/wiki/Getting-Started
"tmux/.tmux.conf" = "~/.tmux.conf"

